SELECT C.ID, CASE
WHEN C.CK <= 0.25 THEN 'CRITICAL'
WHEN C.CK <= 0.50 THEN 'HIGH'
WHEN C.CK <= 0.75 THEN 'MEDIUM'
ELSE 'LOW' END AS COLONY_NAME
FROM (SELECT ID,
PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS CK
FROM ECOLI_DATA) C
JOIN ECOLI_DATA D
ON C.ID = D.ID
ORDER BY C.ID