SELECT C.CAR_ID, CASE 
WHEN C.CAR_ID IN (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY D
WHERE
D.START_DATE <= '2022-10-16' 
AND D.END_DATE >= '2022-10-16'
GROUP BY D.CAR_ID) THEN '대여중'
ELSE '대여 가능'
END AS 'TEST'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC