SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
JOIN ITEM_INFO F
ON T.PARENT_ITEM_ID = F.ITEM_ID
WHERE T.PARENT_ITEM_ID IS NOT NULL AND F.RARITY = 'RARE' 
ORDER BY I.ITEM_ID DESC