SELECT COUNT(FISH_INFO.FISH_TYPE) AS FISH_COUNT, MAX(FISH_INFO.LENGTH) AS MAX_LENGTH, FISH_INFO.FISH_TYPE
FROM FISH_INFO
WHERE FISH_INFO.FISH_TYPE IN 
(
SELECT I.FISH_TYPE
FROM FISH_INFO I
GROUP BY I.FISH_TYPE
HAVING AVG(IFNULL(I.LENGTH, 10)) >= 33
)
GROUP BY FISH_INFO.FISH_TYPE
ORDER BY FISH_INFO.FISH_TYPE ASC